apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-healing-agent-sa
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: healing-dashboard-sa
  namespace: {{ .Values.namespace }}
